### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by mxplusb** [cloudfoundry/nfsbroker#9]
It would be helpful to downstream consumers who don't use this as a bosh release if it was versioned so downstream consumers can version lock their consumption of this. Relates to #8 and #5

**Comment by julian-hj** [comment]
Hi @mxplusb thanks for raising this.  As @DennisDenuto explains in #8, we use the nfs-volume-release bosh release for all build and test.  So, while we could drop release tags onto the nfsbroker repo when we cut new releases of the bosh release, those release markers wouldn't really have any meaning unless we also built and tested the broker using those markers.  

It may be a little unconventional, but it's fairly quick and straightforward to fetch a release label of the bosh release, and then fetch all the submodules with the `scripts/update` script.
